name: Build and Push Container

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            platform: linux/amd64
            arch: amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
            arch: arm64

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Get commit timestamp
        id: commit-info
        run: |
          TIMESTAMP=$(git log -1 --format=%cI ${{ github.sha }})
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Build image
        id: build
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.arch }}
          TIMESTAMP=${{ steps.commit-info.outputs.timestamp }}
          mkdir artifacts
          podman build \
            --build-arg BUILD_TIMESTAMP="${TIMESTAMP}" \
            --build-arg VCS_REF="${{ github.sha }}" \
            --build-arg VCS_URL="${{ github.server_url }}/${{ github.repository }}" \
            --file ./Containerfile \
            --platform ${{ matrix.platform }} \
            --squash \
            --tag ${IMAGE} \
            --timestamp $(date -d "${TIMESTAMP}" +%s) \
            .

      - name: Push image
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.arch }}
          podman push ${IMAGE} \
            --digestfile artifacts/digest.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: artifacts-${{ github.sha }}-${{ matrix.arch }}
          path: artifacts
          retention-days: 1


  merge:
    runs-on: ubuntu-24.04
    needs: [build]
    permissions:
      # contents: read
      packages: write
      id-token: write

    steps:
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Log in to Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Download artifacts
        uses: actions/download-artifact@v6

      - name: Pull ARM image by digest for debugging
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          AMD_DIGEST=`cat artifacts-${{ github.sha }}-amd64/digest.txt`
          ARM_DIGEST=`cat artifacts-${{ github.sha }}-arm64/digest.txt`
          ARM_IMAGE=${IMAGE}@${ARM_DIGEST}
          echo Digest for AMD: ${AMD_DIGEST} for ARM: ${ARM_DIGEST}
          echo Image for AMD: ${AMD_IMAGE} for ARM: ${ARM_IMAGE}
          podman pull ${IMAGE}@${AMD_DIGEST}
          podman pull ${IMAGE}@${ARM_DIGEST}

      - name: Pull architecture-specific containers
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          podman pull ${IMAGE}-amd64
          podman pull ${IMAGE}-arm64

      - name: Create and push manifests
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          IMAGE_SHA=${IMAGE}:${{ github.sha }}
          IMAGE_LATEST=${IMAGE}:latest

          AMD_DIGEST=`cat artifacts-${{ github.sha }}-amd64/digest.txt`
          ARM_DIGEST=`cat artifacts-${{ github.sha }}-arm64/digest.txt`

          podman manifest create ${IMAGE_SHA}
          podman manifest add ${IMAGE_SHA} ${IMAGE_SHA}-amd64
          podman manifest add ${IMAGE_SHA} ${IMAGE_SHA}-arm64
          podman manifest push ${IMAGE_SHA}

          podman manifest create ${IMAGE_LATEST}
          podman manifest ${IMAGE_LATEST} ${IMAGE_SHA}-amd64
          podman manifest ${IMAGE_LATEST} ${IMAGE_SHA}-arm64
          podman manifest push ${IMAGE}:latest
