name: Build and Push Container

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            platform: linux/amd64
            arch: amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
            arch: arm64

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Get commit timestamp
        id: commit
        run: |
          TIMESTAMP=$(git log -1 --format=%cI ${{ github.sha }})
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Build image
        id: build
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.arch }}
          podman build \
            --platform ${{ matrix.platform }} \
            --build-arg BUILD_TIMESTAMP="${{ steps.commit.outputs.timestamp }}" \
            --build-arg VCS_REF="${{ github.sha }}" \
            --build-arg VCS_URL="${{ github.server_url }}/${{ github.repository }}" \
            --squash \
            -f ./Containerfile \
            -t $IMAGE \
            .
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Compute artifacts
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.arch }}
          mkdir artifacts
          podman inspect ${IMAGE} --format='{{.Id}}' > artifacts/id.txt
          podman inspect ${IMAGE} --format='{{.Digest}}' > artifacts/digest.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: artifacts-${{ github.sha }}-${{ matrix.arch }}
          path: artifacts
          retention-days: 1

      - name: Push image
        run: |
          podman push ${{ steps.build.outputs.image }}

  merge:
    runs-on: ubuntu-24.04
    needs: [build]
    permissions:
      # contents: read
      packages: write
      id-token: write

    steps:
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Log in to Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Download artifacts of previous build phases
        uses: actions/download-artifact@v6

      - name: List directory contents for debugging
        run: |
          ls -l

      - name: List ARM artifacts for debugging
        run: |
          ls -l artifacts-${{ github.sha }}-arm64

      - name: Pull architecture-specific containers
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          podman pull ${IMAGE}-amd64
          podman pull ${IMAGE}-arm64

      - name: Create and push manifest with sha tag
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          podman manifest create ${IMAGE}
          podman manifest add ${IMAGE} ${IMAGE}-amd64
          podman manifest add ${IMAGE} ${IMAGE}-arm64
          podman manifest push ${IMAGE}
