name: Container Build

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build architecture-specific images
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            platform: linux/amd64
            arch: amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
            arch: arm64

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Get commit timestamp
        id: commit-info
        run: |
          TIMESTAMP=$(git log -1 --format=%cI ${{ github.sha }})
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Build image
        id: build
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.arch }}
          TIMESTAMP=${{ steps.commit-info.outputs.timestamp }}
          mkdir artifacts
          podman build \
            --build-arg BUILD_TIMESTAMP="${TIMESTAMP}" \
            --build-arg VCS_REF="${{ github.sha }}" \
            --build-arg VCS_URL="${{ github.server_url }}/${{ github.repository }}" \
            --file ./Containerfile \
            --platform ${{ matrix.platform }} \
            --squash \
            --tag ${IMAGE} \
            --timestamp $(date -d "${TIMESTAMP}" +%s) \
            .

      - name: Push image
        id: push
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.arch }}
          podman push ${IMAGE} \
            --digestfile artifacts/digest.txt

      - name: Upload image digests to artifacts
        uses: actions/upload-artifact@v6
        with:
          name: artifacts-${{ matrix.arch }}
          path: artifacts
          retention-days: 3

  manifest:
    name: Build multi-architecture manifest
    runs-on: ubuntu-24.04
    needs: [build]
    permissions:
      id-token: write
      packages: write

    steps:
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Log in to Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Download artifacts
        uses: actions/download-artifact@v7

      - name: Pull architecture-specific images
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          podman pull ${IMAGE}@`cat artifacts-amd64/digest.txt`
          podman pull ${IMAGE}@`cat artifacts-arm64/digest.txt`

      - name: Create and push multi-architecture manifest
        id: manifests
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          IMAGE_AMD64=${IMAGE}@`cat artifacts-amd64/digest.txt`
          IMAGE_ARM64=${IMAGE}@`cat artifacts-arm64/digest.txt`

          mkdir artifacts

          IMAGE_SHA=${IMAGE}:${{ github.sha }}
          podman manifest create ${IMAGE_SHA}
          podman manifest add ${IMAGE_SHA} ${IMAGE_AMD64}
          podman manifest add ${IMAGE_SHA} ${IMAGE_ARM64}
          podman tag ${IMAGE_SHA} ${IMAGE}:latest
          podman manifest push ${IMAGE_SHA} \
              --all \
              --digestfile artifacts/digest.txt

      - name: Upload manifest digest to artifacts
        uses: actions/upload-artifact@v6
        with:
          name: artifacts-manifest
          path: artifacts
          retention-days: 3


  # If you ever refactor the GitHub workflow, make sure that the attest phase
  # continues to run on a separate machine, decoupled from any build jobs.
  # https://slsa.dev/spec/v1.2/build-track-basics#build-l3
  attest:
    name: Attest build provenance
    runs-on: ubuntu-24.04
    needs: [manifest]

    permissions:
      attestations: write
      id-token: write
      packages: write

    steps:
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
        uses: actions/download-artifact@v7

      - name: Retrieve digests
        id: retrieve-digests
        run: |
          echo amd64_digest=`cat artifacts-amd64/digest.txt` >> $GITHUB_OUTPUT
          echo arm64_digest=`cat artifacts-arm64/digest.txt` >> $GITHUB_OUTPUT
          echo manifest_digest=`cat artifacts-manifest/digest.txt` >> $GITHUB_OUTPUT

      - name: Attest amd64 container
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.retrieve-digests.outputs.amd64_digest }}
          push-to-registry: true

      - name: Attest arm64 container
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.retrieve-digests.outputs.arm64_digest }}
          push-to-registry: true

      - name: Attest manifest
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.retrieve-digests.outputs.manifest_digest }}
          push-to-registry: true
