name: Build and Push Container

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            platform: linux/amd64
            arch: amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
            arch: arm64

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Get commit timestamp
        id: commit-info
        run: |
          TIMESTAMP=$(git log -1 --format=%cI ${{ github.sha }})
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Build image
        id: build
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.arch }}
          TIMESTAMP=${{ steps.commit-info.outputs.timestamp }}
          mkdir artifacts
          podman build \
            --build-arg BUILD_TIMESTAMP="${TIMESTAMP}" \
            --build-arg VCS_REF="${{ github.sha }}" \
            --build-arg VCS_URL="${{ github.server_url }}/${{ github.repository }}" \
            --file ./Containerfile \
            --platform ${{ matrix.platform }} \
            --squash \
            --tag ${IMAGE} \
            --timestamp $(date -d "${TIMESTAMP}" +%s) \
            .

      - name: Push image
        id: push
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.arch }}
          podman push ${IMAGE} \
            --digestfile artifacts/digest.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: artifacts-${{ matrix.arch }}
          path: artifacts
          retention-days: 3

  merge:
    runs-on: ubuntu-24.04
    needs: [build]
    permissions:
      id-token: write
      packages: write

    outputs:
      latest_digest: ${{ steps.manifests.outputs.latest_digest }}
      sha_digest: ${{ steps.manifests.outputs.sha_digest }}

    steps:
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Log in to Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Download artifacts
        uses: actions/download-artifact@v6

      - name: Pull architecture-specific images
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          podman pull ${IMAGE}@`cat artifacts-amd64/digest.txt`
          podman pull ${IMAGE}@`cat artifacts-arm64/digest.txt`

      - name: Create and push manifests
        id: manifests
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          IMAGE_AMD64=${IMAGE}@`cat artifacts-amd64/digest.txt`
          IMAGE_ARM64=${IMAGE}@`cat artifacts-arm64/digest.txt`

          IMAGE_SHA=${IMAGE}:${{ github.sha }}
          podman manifest create ${IMAGE_SHA}
          podman manifest add ${IMAGE_SHA} ${IMAGE_AMD64}
          podman manifest add ${IMAGE_SHA} ${IMAGE_ARM64}
          podman manifest push ${IMAGE_SHA} --digestfile=sha.digest
          echo sha_digest=`cat sha.digest.txt` >> $GITHUB_OUTPUT

          IMAGE_LATEST=${IMAGE}:latest
          podman manifest create ${IMAGE_LATEST}
          podman manifest add ${IMAGE_LATEST} ${IMAGE_AMD64}
          podman manifest add ${IMAGE_LATEST} ${IMAGE_ARM64}
          podman manifest push ${IMAGE_LATEST}
          podman manifest push ${IMAGE_SHA} --digestfile=latest.digest
          echo latest_digest=`cat sha.digest.txt` >> $GITHUB_OUTPUT


  # As per SLSA level 3, attestation *must* run decoupled from build jobs.
  attest:
    runs-on: ubuntu-24.04
    needs: [merge]

    permissions:
      attestations: write
      id-token: write
      packages: write

    steps:
      - name: Login to Container Registry
        # actions/attest-build-provenance@v3 (below) needs docker,
        # it does not seem to work with podman.
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
        uses: actions/download-artifact@v6

      - name: Retrieve digests
        id: retrieve-digests
        run: |
          echo amd64_digest=`cat artifacts-amd64/digest.txt` >> $GITHUB_OUTPUT
          echo arm64_digest=`cat artifacts-arm64/digest.txt` >> $GITHUB_OUTPUT

      - name: Attest amd64 container
        uses: actions/attest-build-provenance@v3
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.retrieve-digests.outputs.amd64_digest }}
          push-to-registry: true

      - name: Attest arm64 container
        uses: actions/attest-build-provenance@v3
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.retrieve-digests.outputs.arm64_digest }}
          push-to-registry: true

      - name: Attest multi-arch commit-sha manifest
        uses: actions/attest-build-provenance@v3
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ needs.merge.outputs.sha_digest }}
          push-to-registry: true

      - name: Attest multi-arch latest manifest
        uses: actions/attest-build-provenance@v3
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ needs.merge.outputs.latest_digest }}
          push-to-registry: true
