name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Execute unit and integration tests
    runs-on: ubuntu-latest
    permissions: {}

    steps:
    - name: Check out repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - name: Install Rust LLVM tools preview
      run: rustup component add llvm-tools-preview
    - name: Install Rust coverage tool
      uses: taiki-e/install-action@81a2f66614862089b24532663f669a485d79c889 # v2.67.10
      with:
        tool: cargo-llvm-cov
    - name: Fetch Rust dependencies
      run: cargo fetch --locked
    - name: Check formatting
      run: cargo fmt --check
    - name: Build
      run: cargo build --locked
    - name: Run tests
      run: |
        cargo llvm-cov test --cobertura --locked --verbose --output-path cobertura.xml
    - name: Look for common mistakes
      run: cargo clippy --locked
    - name: Upload test coverage to Coveralls
      uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b  # v2.3.6
